import tls from 'node:tls'
import { verifyDns } from '@/lib/domains'
import { prisma } from '@/lib/prisma'

type ProviderResult = { provisioned: boolean; certificateId?: string; error?: string }
export type TlsState = 'provisioning' | 'active' | 'renewal_due' | 'renewal_in_progress' | 'failed'
export function nextTlsState(input: { dnsOk:boolean; probeOk:boolean; expiresAt:Date|null; now:Date; providerSucceeded:boolean; current?:TlsState }): TlsState {
  if (!input.dnsOk) return 'provisioning'
  if (!input.probeOk) return input.providerSucceeded ? 'renewal_in_progress' : 'failed'
  const expires = input.expiresAt?.getTime() ?? 0
  const remaining = expires - input.now.getTime()
  if (remaining <= 0) return input.providerSucceeded ? 'renewal_in_progress' : 'failed'
  if (remaining <= 14 * 86400_000) return input.current === 'renewal_due' && input.providerSucceeded ? 'renewal_in_progress' : (input.current === 'renewal_in_progress' && input.providerSucceeded ? 'renewal_in_progress' : 'renewal_due')
  return 'active'
}
async function probeTls(host:string):Promise<{ok:boolean;expiresAt:Date|null}>{return new Promise(resolve=>{const socket=tls.connect({host,port:443,servername:host,rejectUnauthorized:true,timeout:5000},()=>{const cert=socket.getPeerCertificate();const expires=cert.valid_to?new Date(cert.valid_to):null;socket.end();resolve({ok:true,expiresAt:expires})});socket.on('error',()=>resolve({ok:false,expiresAt:null}));socket.on('timeout',()=>{socket.destroy();resolve({ok:false,expiresAt:null})})})}
async function vercel(host:string,renew:boolean):Promise<ProviderResult>{if(!process.env.VERCEL_TOKEN||!process.env.VERCEL_PROJECT_ID)return {provisioned:false,error:'VERCEL_TOKEN and VERCEL_PROJECT_ID are required'};try{const qs=process.env.VERCEL_TEAM_ID?`?teamId=${encodeURIComponent(process.env.VERCEL_TEAM_ID)}`:'';const url=`https://api.vercel.com/v9/projects/${encodeURIComponent(process.env.VERCEL_PROJECT_ID)}/domains${qs}`;const res=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${process.env.VERCEL_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({name:host}),signal:AbortSignal.timeout(5000)});if(!res.ok&&res.status!==409)return {provisioned:false,error:`Vercel returned ${res.status}`};return {provisioned:true,certificateId:`vercel:${host}:${renew?'renew':'ensure'}`}}catch(e){return {provisioned:false,error:e instanceof Error?e.message:'Vercel request failed'}}}
async function cloudflare(host:string,renew:boolean):Promise<ProviderResult>{const token=process.env.CLOUDFLARE_API_TOKEN,zone=process.env.CLOUDFLARE_ZONE_ID;if(!token||!zone)return {provisioned:false,error:'CLOUDFLARE_API_TOKEN and CLOUDFLARE_ZONE_ID are required'};try{const res=await fetch(`https://api.cloudflare.com/client/v4/zones/${zone}/custom_hostnames`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({hostname:host,ssl:{method:'http',type:'dv',settings:{min_tls_version:'1.2'}}}),signal:AbortSignal.timeout(5000)});if(res.ok)return {provisioned:true,certificateId:(await res.json() as {result?:{id?:string}}).result?.id};if(res.status===409)return {provisioned:true,certificateId:`cloudflare:${host}:${renew?'renew':'ensure'}`};return {provisioned:false,error:`Cloudflare returned ${res.status}`}}catch(e){return {provisioned:false,error:e instanceof Error?e.message:'Cloudflare request failed'}}}
async function custom(host:string,renew:boolean):Promise<ProviderResult>{const endpoint=process.env.TLS_PROVIDER_WEBHOOK_URL;if(!endpoint)return {provisioned:false,error:'TLS_PROVIDER_WEBHOOK_URL is required for custom TLS provider'};try{const res=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','authorization':process.env.TLS_PROVIDER_WEBHOOK_TOKEN?`Bearer ${process.env.TLS_PROVIDER_WEBHOOK_TOKEN}`:'none'},body:JSON.stringify({hostname:host,action:renew?'renew_certificate':'ensure_certificate'}),signal:AbortSignal.timeout(5000)});if(!res.ok)return {provisioned:false,error:`Custom TLS provider returned ${res.status}`};const body=await res.json().catch(()=>({})) as {certificateId?:string};return {provisioned:true,certificateId:body.certificateId||`custom:${host}`}}catch(e){return {provisioned:false,error:e instanceof Error?e.message:'Custom TLS request failed'}}}
async function provision(provider:string,host:string,renew:boolean){if(provider==='vercel')return vercel(host,renew);if(provider==='cloudflare')return cloudflare(host,renew);if(provider==='custom')return custom(host,renew);return {provisioned:false,error:`Unsupported TLS provider: ${provider}`}}
export async function reconcileDomain(domainId:string){const d=await prisma.brandedDomain.findUnique({where:{id:domainId},include:{provision:true}});if(!d)return null;const dnsOk=await verifyDns(d.host,d.verificationToken).catch(()=>false);if(!dnsOk){await prisma.domainProvision.update({where:{domainId},data:{status:'verifying',checkedAt:new Date(),lastError:'DNS verification record not found'}}).catch(()=>{});return {status:'verifying',dnsOk:false}}const now=new Date();const provider=d.tlsProvider||'vercel';const previous=d.provision?.status as TlsState|undefined;const due=previous==='renewal_due'||Boolean(d.tlsCertificateExpiresAt&&d.tlsCertificateExpiresAt.getTime()-now.getTime()<=14*86400_000);const claimed=due?await prisma.domainProvision.updateMany({where:{domainId,status:{in:['active','renewal_due','provisioning','failed']},OR:[{nextRenewalAt:null},{nextRenewalAt:{lte:now}}]},data:{status:'renewal_in_progress',checkedAt:now}}):{count:0};const renewing=due&&claimed.count===1;const result=await provision(provider,d.host,renewing);const cert=await probeTls(d.host);const state=nextTlsState({dnsOk,probeOk:cert.ok,expiresAt:cert.expiresAt,now,providerSucceeded:result.provisioned,current:previous});const effectiveState=renewing&&result.provisioned&&state==='renewal_due'?'renewal_in_progress':state;const attempts=(d.provision?.renewalAttempts||0)+(renewing?1:0);const nextRenewalAt=effectiveState==='renewal_in_progress'?new Date(now.getTime()+15*60_000):effectiveState==='renewal_due'?new Date(now.getTime()+6*3600_000):null;const error=result.error||(effectiveState==='failed'?'TLS certificate is not currently valid':null);await prisma.$transaction([prisma.brandedDomain.update({where:{id:domainId},data:{status:'verified',verifiedAt:d.verifiedAt||now,lastCheckedAt:now,tlsReady:effectiveState==='active',tlsProvider:provider,tlsStatus:effectiveState,tlsCertificateExpiresAt:cert.expiresAt,tlsLastCheckedAt:now}}),prisma.domainProvision.update({where:{domainId},data:{status:effectiveState,certificateProvider:provider,certificateId:result.certificateId||d.provision?.certificateId,checkedAt:now,activatedAt:effectiveState==='active'?(d.provision?.activatedAt||now):undefined,renewalAttempts:attempts,nextRenewalAt,lastError:error}})]);return {status:effectiveState,dnsOk:true,tlsReady:effectiveState==='active',certificateExpiresAt:cert.expiresAt,provider,renewalDue:due,error}}

