import { SAML } from '@node-saml/node-saml'
import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto'
import { prisma } from '@/lib/prisma'
import { createSession, hashPassword, setSessionCookie } from '@/lib/auth'
import type { NextRequest, NextResponse } from 'next/server'
type SsoProfile=Record<string,unknown>;type Relay={connectionId:string;nonce:string;returnTo:string;exp:number}
function ssoSecret(){const s=process.env.SSO_STATE_SECRET||process.env.QL_ATTRIBUTION_SECRET;if(!s)throw new Error('SSO_STATE_SECRET is required');return s}
export async function createSamlRelayState(connectionId:string,returnTo:string){const state={connectionId,nonce:randomBytes(16).toString('hex'),returnTo:/^\/(?!\/)/.test(returnTo)?returnTo:'/dashboard',exp:Date.now()+300000} satisfies Relay;await prisma.samlRelayNonce.deleteMany({where:{expiresAt:{lte:new Date()}}});await prisma.samlRelayNonce.create({data:{nonce:state.nonce,connectionId:state.connectionId,expiresAt:new Date(state.exp)}});const body=Buffer.from(JSON.stringify(state)).toString('base64url');return `${body}.${createHmac('sha256',ssoSecret()).update(body).digest('base64url')}`}
export async function verifySamlRelayState(value:string,connectionId:string):Promise<Relay|null>{try{const [body,sig]=value.split('.'),expected=createHmac('sha256',ssoSecret()).update(body).digest('base64url');if(!body||!sig||sig.length!==expected.length||!timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const state=JSON.parse(Buffer.from(body,'base64url').toString()) as Relay;if(state.connectionId!==connectionId||state.exp<=Date.now()||!/^\/(?!\/)/.test(state.returnTo)||typeof state.nonce!=='string'||!state.nonce)return null;const consumed=await prisma.samlRelayNonce.updateMany({where:{nonce:state.nonce,connectionId,consumedAt:null,expiresAt:{gt:new Date()}},data:{consumedAt:new Date()}});return consumed.count===1?state:null}catch{return null}}
function validate(c:{ssoUrl:string;entityId:string;idpEntityId:string;x509Certificate:string}){const u=new URL(c.ssoUrl);if(u.protocol!=='https:')throw new Error('SAML SSO URL must use HTTPS');if(!c.entityId||!c.idpEntityId||!c.x509Certificate.includes('BEGIN CERTIFICATE'))throw new Error('Invalid SAML issuer/certificate configuration')}
export async function samlFor(id:string){const c=await prisma.ssoConnection.findUnique({where:{id}});if(!c||!c.enabled)throw new Error('SSO connection is not enabled');validate(c);return new SAML({entryPoint:c.ssoUrl,idpCert:c.x509Certificate,issuer:c.entityId,idpIssuer:c.idpEntityId,callbackUrl:`${process.env.APP_URL||''}/api/sso/saml/${id}/acs`,wantAssertionsSigned:true,wantAuthnResponseSigned:true,acceptedClockSkewMs:5000})}
export async function createSsoSession(profile:SsoProfile,workspaceId:string,request:NextRequest,response:NextResponse,connectionId?:string){const email=String(profile.email||profile.nameID||'').trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error('SAML response did not contain a valid email');const c=connectionId?await prisma.ssoConnection.findFirst({where:{id:connectionId,workspaceId,enabled:true}}):await prisma.ssoConnection.findFirst({where:{workspaceId,enabled:true}});if(c?.allowedDomains){const domains=(c as typeof c & { allowedDomains?: string }).allowedDomains.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(domains.length&&!domains.some(d=>email.endsWith(`@${d}`)))throw new Error('Email domain is not allowed')}let user=await prisma.user.findUnique({where:{email}});if(!user)user=await prisma.user.create({data:{email,name:String(profile.displayName||profile.name||'')||null,password:await hashPassword(randomBytes(32).toString('base64url')),emailVerifiedAt:new Date()}});await prisma.membership.upsert({where:{workspaceId_userId:{workspaceId,userId:user.id}},create:{workspaceId,userId:user.id,role:'viewer'},update:{}});const session=await createSession(user.id,request.headers.get('user-agent'));setSessionCookie(response,session.token,session.expiresAt);return user}


