import { describe, expect, it } from 'vitest'
import { parseScimFilter, parseScimPatchOperations, scimFilterMatches } from './scim'
describe('SCIM RFC filter grammar', () => {
 const r={id:'1',userName:'Ada@example.com',active:true,name:{familyName:'Lovelace',givenName:'Ada'},emails:[{value:'ada@example.com',type:'work'},{value:'ada@personal.test',type:'home'}]}
 it('comparisons',()=>{expect(scimFilterMatches(r,parseScimFilter('userName co "@example.com"')!)).toBe(true);expect(scimFilterMatches(r,parseScimFilter('active eq true')!)).toBe(true);expect(scimFilterMatches(r,parseScimFilter('title pr')!)).toBe(false);expect(scimFilterMatches(r,parseScimFilter('name.familyName sw "Love"')!)).toBe(true)})
 it('logic has RFC precedence',()=>{expect(scimFilterMatches(r,parseScimFilter('active eq true or active eq false and title pr')!)).toBe(true);expect(scimFilterMatches(r,parseScimFilter('active eq true and userName sw "Ada"')!)).toBe(true);expect(scimFilterMatches(r,parseScimFilter('not (active eq false)')!)).toBe(true)})
 it('valuePath and ordering',()=>{expect(scimFilterMatches(r,parseScimFilter('emails[type eq "work" and value co "example"]')!)).toBe(true);expect(scimFilterMatches(r,parseScimFilter('name.givenName gt "Aaa"')!)).toBe(true);expect(scimFilterMatches(r,parseScimFilter('name.givenName le "Ada"')!)).toBe(true)})
 it('supports schema-qualified attributes and JSON strings',()=>{expect(scimFilterMatches({userName:'Ada'},parseScimFilter('urn:ietf:params:scim:schemas:core:2.0:User:userName eq "ada"')!)).toBe(true);expect(scimFilterMatches({userName:'a"b'},parseScimFilter('userName eq "a\\\"b"')!)).toBe(true);expect(scimFilterMatches({userName:'Ada\nLovelace'},parseScimFilter('userName eq "Ada\\nLovelace"')!)).toBe(true)})
 it('uses type-safe comparisons and RFC missing-attribute semantics',()=>{expect(scimFilterMatches({active:true},parseScimFilter('active eq true')!)).toBe(true);expect(scimFilterMatches({active:true},parseScimFilter('active eq "true"')!)).toBe(false);expect(scimFilterMatches({},parseScimFilter('missing ne "x"')!)).toBe(false);expect(scimFilterMatches({age:10},parseScimFilter('age gt 2')!)).toBe(true)})
 it('rejects malformed and hostile filters',()=>{for(const f of ['userName eq "a" and','userName nope "a"','userName eq \'a\'','userName eq "bad\\q"','userName eq "\\uZZZZ"','name..familyName eq "x"','emails[type eq "work"][value eq "x"]'])expect(()=>parseScimFilter(f)).toThrow();expect(()=>parseScimFilter('('.repeat(100)+'active pr'+')'.repeat(100))).toThrow();expect(()=>parseScimFilter('x eq "a"'.repeat(2000))).toThrow();expect(()=>parseScimPatchOperations({Operations:[{op:'increment'}]})).toThrow()})
})
