import { Text, View, Pressable, StyleSheet, TextInput, ActivityIndicator } from 'react-native'
import { useEffect, useState } from 'react'
import { api, saveSession, getSession, clearSession } from './api'
const BASE=(process.env.EXPO_PUBLIC_API_URL||'http://127.0.0.1:3000').replace(/\/$/,'')
export default function Home(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [logged,setLogged]=useState(false);const [busy,setBusy]=useState(false);const [offline,setOffline]=useState(false);const [error,setError]=useState<string|null>(null);useEffect(()=>{let mounted=true;void getSession().then(t=>{if(mounted)setLogged(Boolean(t))},()=>{if(mounted)setOffline(true)});return()=>{mounted=false}},[])
async function login(){const cleanEmail=email.trim();if(!/.+@.+\..+/.test(cleanEmail)){setError('Enter a valid email address.');return}if(!password){setError('Enter your password.');return}setBusy(true);setError(null);setOffline(false);let body:{token?:unknown};try{body=await api(BASE,'/api/auth/login',{method:'POST',headers:{'x-mobile-client':'1'},body:JSON.stringify({email:cleanEmail,password})}) as {token?:unknown}}catch(e){if(typeof (e as {status?:unknown})?.status==='number')setError(e instanceof Error?e.message:'Sign-in failed.');else setOffline(true);return}finally{setBusy(false)}if(typeof body?.token!=='string'||!body.token){setError('Sign-in did not return a session. Please try again.');return}try{await saveSession(body.token as string)}catch{setError('Signed in, but the session could not be saved on this device.');return}setLogged(true)}
return <View style={s.root}><Text style={s.brand}>QuickLink</Text><Text style={s.title}>{logged?'Control plane':'Sign in'}</Text>{!logged?<><TextInput accessibilityLabel="Email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="you@company.com" placeholderTextColor="#64748b" style={s.input}/><TextInput accessibilityLabel="Password" secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor="#64748b" style={s.input}/><Pressable accessibilityRole="button" onPress={()=>void login()} disabled={busy} style={s.button}>{busy?<ActivityIndicator/>:<Text style={s.buttonText}>Sign in</Text>}</Pressable></>:<><Text style={s.copy}>You are authenticated. Deep links and push notifications are enabled.</Text><Pressable accessibilityRole="button" onPress={()=>void clearSession().then(()=>setLogged(false),()=>setError('Could not sign out on this device. Please try again.'))} style={s.secondary}><Text style={s.buttonText}>Sign out</Text></Pressable></>}{error&&<Text accessibilityLiveRegion="polite" style={s.error}>{error}</Text>}{offline&&<Text accessibilityLiveRegion="polite" style={s.offline}>Offline or unreachable. Check your connection and try again.</Text>}</View>}
const s=StyleSheet.create({root:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#020617'},brand:{color:'#93c5fd',fontWeight:'700',fontSize:16},title:{color:'#fff',fontSize:32,fontWeight:'700',marginVertical:18},copy:{color:'#94a3b8',fontSize:16,lineHeight:24},input:{backgroundColor:'#0f172a',color:'#fff',borderColor:'#334155',borderWidth:1,borderRadius:12,padding:14,marginBottom:12},button:{marginTop:8,backgroundColor:'#fff',padding:15,borderRadius:12,alignItems:'center'},secondary:{marginTop:24,borderColor:'#475569',borderWidth:1,padding:15,borderRadius:12,alignItems:'center'},buttonText:{color:'#020617',fontWeight:'700'},error:{color:'#fca5a5',marginTop:18},offline:{color:'#fbbf24',marginTop:18}})

