import { Text, View, Pressable, StyleSheet, TextInput, ActivityIndicator } from 'react-native'
import { useEffect, useState } from 'react'
import { api, saveSession, getSession, clearSession } from './api'
import * as Linking from 'expo-linking'
const BASE=process.env.EXPO_PUBLIC_API_URL||'http://127.0.0.1:3000'
export default function Home(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [logged,setLogged]=useState(false);const [busy,setBusy]=useState(false);const [offline,setOffline]=useState(false);useEffect(()=>{void getSession().then(t=>setLogged(Boolean(t)));const sub=Linking.addEventListener('url',()=>setOffline(false));return()=>sub.remove()},[])
async function login(){setBusy(true);try{const r=await fetch(`${BASE}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json','x-mobile-client':'1'},body:JSON.stringify({email,password})});if(!r.ok)throw new Error('Invalid credentials');const b=await r.json();if(b.token)await saveSession(b.token);setLogged(true)}catch(e){setOffline(true)}finally{setBusy(false)}}
return <View style={s.root}><Text style={s.brand}>QuickLink</Text><Text style={s.title}>{logged?'Control plane':'Sign in'}</Text>{!logged?<><TextInput accessibilityLabel="Email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="you@company.com" placeholderTextColor="#64748b" style={s.input}/><TextInput accessibilityLabel="Password" secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor="#64748b" style={s.input}/><Pressable accessibilityRole="button" onPress={()=>void login()} disabled={busy} style={s.button}>{busy?<ActivityIndicator/>:<Text style={s.buttonText}>Sign in</Text>}</Pressable></>:<><Text style={s.copy}>You are authenticated. Deep links and push notifications are enabled.</Text><Pressable accessibilityRole="button" onPress={()=>void clearSession().then(()=>setLogged(false))} style={s.secondary}><Text style={s.buttonText}>Sign out</Text></Pressable></>}{offline&&<Text accessibilityLiveRegion="polite" style={s.offline}>Offline or unreachable. Your session stays local.</Text>}</View>}
const s=StyleSheet.create({root:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#020617'},brand:{color:'#93c5fd',fontWeight:'700',fontSize:16},title:{color:'#fff',fontSize:32,fontWeight:'700',marginVertical:18},copy:{color:'#94a3b8',fontSize:16,lineHeight:24},input:{backgroundColor:'#0f172a',color:'#fff',borderColor:'#334155',borderWidth:1,borderRadius:12,padding:14,marginBottom:12},button:{marginTop:8,backgroundColor:'#fff',padding:15,borderRadius:12,alignItems:'center'},secondary:{marginTop:24,borderColor:'#475569',borderWidth:1,padding:15,borderRadius:12,alignItems:'center'},buttonText:{color:'#020617',fontWeight:'700'},offline:{color:'#fbbf24',marginTop:18}})

