import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getCurrentUser } from '@/lib/auth'
import { getFeatureFlag } from '@/lib/feature-flags'
import { EDIT_ROLES } from '@/lib/workspaces'
import { recordAudit } from '@/lib/audit'
export async function GET(request:NextRequest,{params}:{params:Promise<{workspaceId:string}>}){const u=await getCurrentUser(request);if(!u)return NextResponse.json({error:'Authentication required'},{status:401});const {workspaceId}=await params;const m=await prisma.membership.findUnique({where:{workspaceId_userId:{workspaceId,userId:u.id}}});if(!m)return NextResponse.json({error:'Forbidden'},{status:403});const rows=await prisma.featureFlag.findMany({where:{workspaceId},orderBy:{key:'asc'}});return NextResponse.json(rows.map(r=>({key:r.key,enabled:r.enabled,rolloutPercent:r.rolloutPercent,config:r.configJson?JSON.parse(r.configJson):{}})))}
export async function PUT(request:NextRequest,{params}:{params:Promise<{workspaceId:string}>}){const u=await getCurrentUser(request);if(!u)return NextResponse.json({error:'Authentication required'},{status:401});const {workspaceId}=await params;const m=await prisma.membership.findUnique({where:{workspaceId_userId:{workspaceId,userId:u.id}}});if(!m||!EDIT_ROLES.includes(m.role))return NextResponse.json({error:'Editor permission required'},{status:403});const b=await request.json().catch(()=>null);if(!b||typeof b.key!=='string'||!/^[-a-z0-9_.]{1,100}$/.test(b.key))return NextResponse.json({error:'Invalid flag key'},{status:400});const rollout=Number(b.rolloutPercent??100);if(!Number.isInteger(rollout)||rollout<0||rollout>100)return NextResponse.json({error:'rolloutPercent must be 0-100'},{status:400});const before=await prisma.featureFlag.findUnique({where:{workspaceId_key:{workspaceId,key:b.key}}}); const row=await prisma.featureFlag.upsert({where:{workspaceId_key:{workspaceId,key:b.key}},create:{workspaceId,key:b.key,enabled:Boolean(b.enabled),rolloutPercent:rollout,configJson:JSON.stringify(b.config??{})},update:{enabled:Boolean(b.enabled),rolloutPercent:rollout,configJson:JSON.stringify(b.config??{})}}); await recordAudit(request,{action:'feature_flag.updated',resourceType:'feature_flag',resourceId:row.id,before:before?{enabled:before.enabled,rolloutPercent:before.rolloutPercent,configJson:before.configJson}:null,after:{enabled:row.enabled,rolloutPercent:row.rolloutPercent,configJson:row.configJson},metadata:{workspaceId,key:row.key}});return NextResponse.json({key:row.key,enabled:row.enabled,rolloutPercent:row.rolloutPercent,config:await getFeatureFlag(row.key,workspaceId)})}


