import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { prisma } from '@/lib/prisma'
import { getCurrentUser } from '@/lib/auth'
import { getDefaultWorkspace } from '@/lib/workspaces'
import { runCampaignAutopilot, createImmutableExperimentSnapshot } from '@/lib/campaigns'
import { publishWorkspaceRoutingConfig } from '@/lib/routing-config'
async function load(request:NextRequest,id:string){const u=await getCurrentUser(request);if(!u)return null;const ws=await getDefaultWorkspace(u.id);if(!ws)return null;return prisma.campaign.findFirst({where:{id,workspaceId:ws.id},include:{variants:true,experiments:{include:{snapshots:{orderBy:{sequence:'desc'},take:20}}},releases:{orderBy:{version:'desc'},take:20,include:{approvals:true}},decisions:{orderBy:{createdAt:'desc'},take:50},anomalies:{orderBy:{createdAt:'desc'},take:50}}})}
export async function GET(request:NextRequest,{params}:{params:Promise<{campaignId:string}>}){const c=await load(request,(await params).campaignId);return c?NextResponse.json(c):NextResponse.json({error:'Not found'},{status:404})}
const patch=z.object({status:z.enum(['draft','scheduled','running','paused','completed','archived']).optional(),autoOptimize:z.boolean().optional(),startAt:z.string().datetime().nullable().optional(),endAt:z.string().datetime().nullable().optional(),objective:z.enum(['conversion_rate','revenue_per_click','revenue','conversion_value']).optional()})
export async function PATCH(request:NextRequest,{params}:{params:Promise<{campaignId:string}>}){const c=await load(request,(await params).campaignId);if(!c)return NextResponse.json({error:'Not found'},{status:404});try{const b=patch.parse(await request.json());const u=await prisma.campaign.update({where:{id:c.id},data:{...b,startAt:b.startAt===undefined?undefined:b.startAt?new Date(b.startAt):null,endAt:b.endAt===undefined?undefined:b.endAt?new Date(b.endAt):null,version:{increment:1}}});await publishWorkspaceRoutingConfig(c.workspaceId);return NextResponse.json(u)}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid request'},{status:400})}}
export async function POST(request:NextRequest,{params}:{params:Promise<{campaignId:string}>}){const c=await load(request,(await params).campaignId);if(!c)return NextResponse.json({error:'Not found'},{status:404});const action=request.nextUrl.searchParams.get('action'),user=await getCurrentUser(request);if(action==='autopilot')return NextResponse.json(await runCampaignAutopilot(c.id,user?.id));if(action==='start'){const e=c.experiments.find(x=>x.status==='draft')||c.experiments[0];if(!e)return NextResponse.json({error:'Experiment missing'},{status:409});await prisma.$transaction([prisma.campaign.update({where:{id:c.id},data:{status:'running'}}),prisma.campaignExperiment.update({where:{id:e.id},data:{status:'running',startedAt:new Date()}})]);await createImmutableExperimentSnapshot(e.id,{campaignId:c.id,variants:c.variants.map(v=>({id:v.id,weight:v.weight,destinationUrl:v.destinationUrl}))},{event:'started'},{actor:user?.id});await publishWorkspaceRoutingConfig(c.workspaceId);return NextResponse.json({ok:true})}return NextResponse.json({error:'Unknown action'},{status:400})}


