import { NextRequest, NextResponse } from 'next/server'
export const runtime='nodejs'
type Rule={enabled:boolean;healthStatus?:string|null;countryCodes?:string|null;deviceType?:string|null;trafficType?:string|null;aiAgent?:string|null;os?:string|null;languageCodes?:string|null;referrerDomain?:string|null;startAt?:string|null;endAt?:string|null;priority:number;weight:number;destinationUrl:string}
type Variant={enabled:boolean;weight:number;destinationUrl:string}
type Campaign={id:string;variants:Variant[]}
type Link={shortCode:string;originalUrl:string;expiresAt:string|null;revision:string|null;rules:Rule[];campaigns:Campaign[]}
type EdgeConfig={previousHash?:string;contentHash:string;signature:string;version?:number;link:Link}
let lastGood:EdgeConfig|null=null
let lastGoodAt=0
function list(v:string|null|undefined){return(v||'').split(/[\s,]+/).filter(Boolean).map(x=>x.toLowerCase())}
function match(r:Rule,c:{country:string;device:string;trafficType:string;aiAgent:string|null;os:string;language:string;referrer:string}){return r.enabled&&r.healthStatus!=='down'&&(!r.countryCodes||list(r.countryCodes).includes(c.country))&&(!r.deviceType||r.deviceType===c.device)&&(!r.trafficType||r.trafficType===c.trafficType)&&(!r.aiAgent||list(r.aiAgent).includes(c.aiAgent||''))&&(!r.os||list(r.os).includes(c.os))&&(!r.languageCodes||list(r.languageCodes).includes(c.language))&&(!r.referrerDomain||c.referrer===r.referrerDomain.toLowerCase())&&(!r.startAt||Date.now()>=Date.parse(r.startAt))&&(!r.endAt||Date.now()<=Date.parse(r.endAt))}
async function bucket(seed:string,total:number){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(seed));const b=new Uint8Array(d);return ((((b[0]<<24)|(b[1]<<16)|(b[2]<<8)|b[3])>>>0)%total)}
async function choose(items:Array<{enabled:boolean;weight:number;destinationUrl:string}>,seed:string){const active=items.filter(v=>v.enabled&&v.weight>0);if(!active.length)return null;const total=active.reduce((n,v)=>n+v.weight,0),n=await bucket(seed,total);let c=0;for(const v of active){c+=v.weight;if(n<c)return v}return active[active.length-1]}
async function verifyConfig(body:EdgeConfig){const secret=process.env.QL_CONFIG_SIGNING_SECRET||process.env.QL_ATTRIBUTION_SECRET;if(!secret)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);const raw=body.signature.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(body.signature.length/4)*4,'=');try{return await crypto.subtle.verify('HMAC',key,Uint8Array.from(atob(raw),c=>c.charCodeAt(0)),new TextEncoder().encode((body.previousHash||'')+'.'+body.contentHash))}catch{return false}}
async function loadConfig(request:NextRequest,shortCode:string){const base=new URL('/api/edge/config/'+encodeURIComponent(shortCode),request.url);const replica=process.env.QL_EDGE_REPLICA_URL;const origins=[replica?new URL('/api/edge/config/'+encodeURIComponent(shortCode),replica).toString():null,base.toString()].filter(Boolean) as string[];for(const target of origins){try{const r=await fetch(target,{headers:{accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(1500)});if(!r.ok)continue;const body=await r.json() as EdgeConfig;if(await verifyConfig(body)){lastGood=body;lastGoodAt=Date.now();return body}}catch{}}if(lastGood&&Date.now()-lastGoodAt<5*60_000)return lastGood;return null}
export async function GET(request:NextRequest,{params}:{params:Promise<{shortCode:string}>}){const {shortCode}=await params;const body=await loadConfig(request,shortCode);if(!body)return new NextResponse('Link configuration unavailable',{status:503,headers:{'Retry-After':'5'}});const link=body.link;const ua=request.headers.get('user-agent')||'';const ai=/GPTBot|OAI-SearchBot|ChatGPT-User/i.test(ua)?'openai':/ClaudeBot|Claude-User/i.test(ua)?'anthropic':/PerplexityBot/i.test(ua)?'perplexity':/Google-Extended|Gemini/i.test(ua)?'google-ai':null;const bot=/bot|crawler|spider|slurp|headless/i.test(ua);const device=/ipad|tablet/i.test(ua)?'tablet':/mobi|iphone|android/i.test(ua)?'mobile':'desktop';const traffic=ai?'ai_agent':bot?'bot':'human';const language=(request.headers.get('accept-language')||'en').split(',')[0].split('-')[0].toLowerCase();const country=(request.headers.get('x-vercel-ip-country')||request.headers.get('cf-ipcountry')||'xx').toLowerCase();let ref='';try{ref=new URL(request.headers.get('referer')||'').hostname.replace(/^www\./,'').toLowerCase()}catch{};let destination=link.revision||link.originalUrl;const campaign=link.campaigns?.find(Boolean);if(campaign){const v=await choose(campaign.variants,`${campaign.id}:${request.headers.get('x-forwarded-for')||ua}`);if(v)destination=v.destinationUrl}const rules=link.rules.filter(r=>match(r,{country,device,trafficType:traffic,aiAgent:ai,os:/iphone|ipad|mac os x/i.test(ua)?'ios':/android/i.test(ua)?'android':/windows/i.test(ua)?'windows':/mac/i.test(ua)?'macos':'other',language,referrer:ref})).sort((a,b)=>a.priority-b.priority);if(rules.length){const v=await choose(rules.filter(r=>r.priority===rules[0].priority),`${shortCode}:${request.headers.get('x-forwarded-for')||ua}`);if(v)destination=v.destinationUrl}if(link.expiresAt&&Date.now()>Date.parse(link.expiresAt))return new NextResponse('Link expired',{status:410});const target=new URL(destination);for(const [k,v] of request.nextUrl.searchParams)if(!target.searchParams.has(k))target.searchParams.set(k,v);return NextResponse.redirect(target,307)}
