ALTER TABLE "click_events" ADD COLUMN IF NOT EXISTS "campaignVariantId" TEXT;
ALTER TABLE "campaign_variants" ADD COLUMN IF NOT EXISTS "valueSquaredCents" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "campaign_experiments" ADD COLUMN IF NOT EXISTS "lookCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "campaign_experiments" ADD COLUMN IF NOT EXISTS "alphaSpent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "campaign_experiments" ADD COLUMN IF NOT EXISTS "lastLookAt" TIMESTAMP(3);
ALTER TABLE "campaign_experiments" ADD COLUMN IF NOT EXISTS "cooldownUntil" TIMESTAMP(3);
ALTER TABLE "campaign_releases" ADD COLUMN IF NOT EXISTS "approvalQuorum" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "campaign_releases" ADD COLUMN IF NOT EXISTS "requiredApprovalRoles" TEXT NOT NULL DEFAULT 'owner';
ALTER TABLE "campaign_release_approvals" ADD COLUMN IF NOT EXISTS "roleSnapshot" TEXT;
ALTER TABLE "routing_config_snapshots" ADD COLUMN IF NOT EXISTS "replicatedAt" TIMESTAMP(3);
ALTER TABLE "routing_config_snapshots" ADD COLUMN IF NOT EXISTS "replicationAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "campaign_anomalies" ADD COLUMN IF NOT EXISTS "fingerprint" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_anomalies_campaignId_fingerprint_startedAt_key" ON "campaign_anomalies"("campaignId","fingerprint","startedAt");
ALTER TABLE "branded_domains" ADD COLUMN IF NOT EXISTS "tlsProvider" TEXT;
ALTER TABLE "branded_domains" ADD COLUMN IF NOT EXISTS "tlsStatus" TEXT;
ALTER TABLE "branded_domains" ADD COLUMN IF NOT EXISTS "tlsCertificateExpiresAt" TIMESTAMP(3);
ALTER TABLE "branded_domains" ADD COLUMN IF NOT EXISTS "tlsLastCheckedAt" TIMESTAMP(3);
ALTER TABLE "webhook_deliveries" ADD COLUMN IF NOT EXISTS "leaseToken" TEXT;
ALTER TABLE "webhook_deliveries" ADD COLUMN IF NOT EXISTS "leaseUntil" TIMESTAMP(3);
ALTER TABLE "sso_connections" ADD COLUMN IF NOT EXISTS "allowedDomains" TEXT;
ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "scopes" TEXT NOT NULL DEFAULT '*';
ALTER TABLE "urls" ADD COLUMN IF NOT EXISTS "deepLinkAppId" TEXT;
ALTER TABLE "deep_link_apps" ADD COLUMN IF NOT EXISTS "iosStoreUrl" TEXT;
ALTER TABLE "deep_link_apps" ADD COLUMN IF NOT EXISTS "androidStoreUrl" TEXT;
CREATE INDEX IF NOT EXISTS "click_events_campaignVariantId_idx" ON "click_events"("campaignVariantId");
CREATE INDEX IF NOT EXISTS "webhook_deliveries_leaseUntil_idx" ON "webhook_deliveries"("leaseUntil");
CREATE INDEX IF NOT EXISTS "branded_domains_tlsStatus_idx" ON "branded_domains"("tlsStatus");
