import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { createHash } from 'node:crypto'
import { prisma } from '@/lib/prisma'
import { getCurrentUser } from '@/lib/auth'
import { getIdempotentResponse, storeIdempotentResponse } from '@/lib/idempotency'
import { rateLimit } from '@/lib/rate-limit'
export const schema=z.object({scheduledAt:z.string().datetime().nullable().optional(),requireApproval:z.boolean().default(true)})
export function isValidScheduledAt(value: string | null | undefined, now: Date = new Date()): boolean {
  if (value == null) return true
  const at = new Date(value)
  if (Number.isNaN(at.getTime())) return false
  return at.getTime() > now.getTime() - 60_000
}
export async function GET(request:NextRequest,{params}:{params:Promise<{campaignId:string}>}){const {campaignId}=await params;const u=await getCurrentUser(request);if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const m=await prisma.membership.findFirst({where:{userId:u.id,workspace:{campaigns:{some:{id:campaignId}}}}});if(!m)return NextResponse.json({error:'Not found'},{status:404});return NextResponse.json(await prisma.campaignRelease.findMany({where:{campaignId},include:{approvals:true},orderBy:{version:'desc'},take:50}))}
export async function POST(request:NextRequest,{params}:{params:Promise<{campaignId:string}>}){const {campaignId}=await params;const u=await getCurrentUser(request);if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const membership=await prisma.membership.findFirst({where:{userId:u.id,workspace:{campaigns:{some:{id:campaignId}}}}});if(!membership||!['owner','admin','editor'].includes(membership.role))return NextResponse.json({error:'Insufficient permissions'},{status:403});const limit=await rateLimit(request,{name:'campaigns-release-create',limit:30,windowMs:60_000});if(!limit.allowed)return NextResponse.json({error:'Too many requests'},{status:429});try{const b=schema.parse(await request.json());if(!isValidScheduledAt(b.scheduledAt))return NextResponse.json({error:'scheduledAt must be in the future'},{status:400});const c=await prisma.campaign.findUnique({where:{id:campaignId},include:{variants:true,workspace:{include:{members:true}}}});if(!c)return NextResponse.json({error:'Not found'},{status:404});const idem=await getIdempotentResponse(request,c.workspaceId,b);if(idem?.existing)return new NextResponse(idem.existing.responseJson,{status:idem.existing.responseStatus,headers:{'Content-Type':'application/json','Idempotent-Replay':'true'}});const version=c.version+1;const config=JSON.stringify({campaignId,version,variants:c.variants.map(v=>({id:v.id,destinationUrl:v.destinationUrl,weight:v.weight,enabled:v.enabled}))});const hash=createHash('sha256').update(config).digest('hex');const eligible=c.workspace.members.filter(x=>x.role==='owner'||x.role==='admin');const hasAdmin=eligible.some(x=>x.role==='admin');const roles=hasAdmin?'owner,admin':'owner';const quorum=hasAdmin?2:1;const release=await prisma.$transaction(async tx=>{const r=await tx.campaignRelease.create({data:{campaignId,version,configJson:config,configHash:hash,scheduledAt:b.scheduledAt?new Date(b.scheduledAt):null,status:b.requireApproval?'pending_approval':'approved',createdById:u.id,approvalQuorum:quorum,requiredApprovalRoles:roles}});if(b.requireApproval)await tx.campaignReleaseApproval.createMany({data:eligible.map(x=>({releaseId:r.id,reviewerUserId:x.userId,roleSnapshot:x.role,status:'pending'}))});return r});if(idem)await storeIdempotentResponse({workspaceId:c.workspaceId,keyHash:idem.keyHash,requestHash:idem.requestHash,method:request.method,path:request.nextUrl.pathname,status:201,body:release});return NextResponse.json(release,{status:201})}catch(e){console.error('Release create failed:',e);if(e instanceof z.ZodError)return NextResponse.json({error:'Invalid release'},{status:400});if(e instanceof Error&&/idempotency-key/i.test(e.message))return NextResponse.json({error:e.message},{status:400});return NextResponse.json({error:'Unable to create release'},{status:400})}}

