import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { createHash } from 'node:crypto'
import { prisma } from '@/lib/prisma'
import { getCurrentUser } from '@/lib/auth'
const schema=z.object({scheduledAt:z.string().datetime().nullable().optional(),requireApproval:z.boolean().default(true)})
export async function GET(request:NextRequest,{params}:{params:Promise<{campaignId:string}>}){const {campaignId}=await params;const u=await getCurrentUser(request);if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const m=await prisma.membership.findFirst({where:{userId:u.id,workspace:{campaigns:{some:{id:campaignId}}}}});if(!m)return NextResponse.json({error:'Not found'},{status:404});return NextResponse.json(await prisma.campaignRelease.findMany({where:{campaignId},include:{approvals:true},orderBy:{version:'desc'}}))}
export async function POST(request:NextRequest,{params}:{params:Promise<{campaignId:string}>}){const {campaignId}=await params;const u=await getCurrentUser(request);if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const membership=await prisma.membership.findFirst({where:{userId:u.id,workspace:{campaigns:{some:{id:campaignId}}}}});if(!membership||!['owner','admin','editor'].includes(membership.role))return NextResponse.json({error:'Insufficient permissions'},{status:403});try{const b=schema.parse(await request.json());const c=await prisma.campaign.findUnique({where:{id:campaignId},include:{variants:true,workspace:{include:{members:true}}}});if(!c)return NextResponse.json({error:'Not found'},{status:404});const version=c.version+1;const config=JSON.stringify({campaignId,version,variants:c.variants.map(v=>({id:v.id,destinationUrl:v.destinationUrl,weight:v.weight,enabled:v.enabled}))});const hash=createHash('sha256').update(config).digest('hex');const eligible=c.workspace.members.filter(x=>x.role==='owner'||x.role==='admin');const hasAdmin=eligible.some(x=>x.role==='admin');const roles=hasAdmin?'owner,admin':'owner';const quorum=hasAdmin?2:1;const release=await prisma.$transaction(async tx=>{const r=await tx.campaignRelease.create({data:{campaignId,version,configJson:config,configHash:hash,scheduledAt:b.scheduledAt?new Date(b.scheduledAt):null,status:b.requireApproval?'pending_approval':'approved',createdById:u.id,approvalQuorum:quorum,requiredApprovalRoles:roles}});if(b.requireApproval)await tx.campaignReleaseApproval.createMany({data:eligible.map(x=>({releaseId:r.id,reviewerUserId:x.userId,roleSnapshot:x.role,status:'pending'}))});return r});return NextResponse.json(release,{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid release'},{status:400})}}

