import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { recordAudit } from '@/lib/audit'
import { getManageableUrl } from '@/lib/authorization'

async function authorize(request: NextRequest, shortCode: string, goalId: string) { const manageable = await getManageableUrl(request, shortCode); if (!manageable.url) return { response: NextResponse.json({ error: manageable.error }, { status: manageable.status }) }; const goal = await prisma.goal.findFirst({ where: { id: goalId, urlId: manageable.url.id } }); if (!goal) return { response: NextResponse.json({ error: 'Goal not found' }, { status: 404 }) }; return { url: manageable.url, goal } }
export async function PATCH(request: NextRequest, context: { params: Promise<{ shortCode: string; goalId: string }> }) { const { shortCode, goalId } = await context.params; const auth = await authorize(request, shortCode, goalId); if ('response' in auth) return auth.response; try { const body = (await request.json()) as Record<string, unknown>; const patch: Record<string, unknown> = {}; if (body.name !== undefined) { const name = typeof body.name === 'string' ? body.name.trim().slice(0, 80) : ''; if (!name) throw new Error('Goal name is required'); patch.name = name } if (body.enabled !== undefined) patch.enabled = Boolean(body.enabled); const before = { name: auth.goal.name, eventKey: auth.goal.eventKey, enabled: auth.goal.enabled }
 const updated = await prisma.goal.update({ where: { id: auth.goal.id }, data: patch }); await recordAudit(request, { action: 'conversion_goal.update', urlId: auth.url.id, resourceType: 'goal', resourceId: auth.goal.id, before, after: { ...before, ...patch } }); return NextResponse.json(updated) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Could not update goal' }, { status: 400 }) } }
export async function DELETE(request: NextRequest, context: { params: Promise<{ shortCode: string; goalId: string }> }) { const { shortCode, goalId } = await context.params; const auth = await authorize(request, shortCode, goalId); if ('response' in auth) return auth.response; await prisma.goal.delete({ where: { id: auth.goal.id } }); await recordAudit(request, { action: 'conversion_goal.delete', urlId: auth.url.id, resourceType: 'goal', resourceId: auth.goal.id, before: { name: auth.goal.name, eventKey: auth.goal.eventKey, enabled: auth.goal.enabled } }); return new NextResponse(null, { status: 204 }) }
